version: 2.1
orbs:
  slack: circleci/slack@4.0.0
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 tests.py
      - store_artifacts:
          path: test-reports/
          destination: python_app
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "Reply yes to confirm merge 321",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
workflows:
  version: 2.1
  on-hold-example:
    jobs:
      - build
      - slack/on-hold:
          requires:
            - build
      - pause_workflow:
          requires:
            - build
            - slack/on-hold
          type: approval
